[package]
name = "zcb3"
version = "3.3.0"
edition = "2021"
authors = ["zeozeozeo"]
build = "build.rs"

[profile.release]
lto = true
strip = true

# rubato is *super* slow in debug builds, so we always build it with O3
[profile.dev.package.rubato]
opt-level = 3

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "bot"]

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
eframe = "0.24.1"
egui-modal = "0.3.1"
env_logger = "0.10.0"
image = { version = "0.24.7", default-features = false, features = ["ico", "png"] }
reqwest = { version = "0.11.22", features = ["blocking"] }
rfd = "0.12.0"
bot = { path = "bot" }
serde_json = "1.0.107"
log = "0.4.20"
anyhow = "1.0.75"
rayon = "1.8.0"
egui_extras = { version = "0.24.1", features = ["image"] }
rustmatica = "0.1.1"
egui_plot = "0.24.1"
serde = "1.0.192"
rand = "0.8.5"
self-replace = "1.3.7"

# needed to hide console window on windows
[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["wincon", "winuser"] }

[build-dependencies]
winres = "0.1"
built = "0.7.0"
