[package]
name = "zcb3"
version = "3.0.8"
edition = "2021"
authors = ["zeozeozeo"]
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "bot"]

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
eframe = "0.23.0"
egui-modal = "0.2.5"
env_logger = "0.10.0"
image = "0.24.7"
reqwest = { version = "0.11.22", features = ["blocking"] }
rfd = "0.12.0"
bot = { path = "bot" }
serde_json = "1.0.107"
log = "0.4.20"
anyhow = "1.0.75"

# needed to hide console window on windows
[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3.9", features = ["wincon", "winuser"] }

[build-dependencies]
winres = "0.1"
built = "0.7.0"
