[package]
name = "bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.77"
base64 = "0.21.5"
bincode = "1.3.3"
byteorder = "1.5.0"
chrono = "0.4.31"
dlhn = "0.1.6"
fasteval2 = { git = "https://github.com/zeozeozeo/fasteval2.git", branch = "sqrt-builtin", default-features = false, features = ["alpha-keywords"]}
hound = "3.5.1"
ijson = "0.1.3"
leb128 = "0.2.5"
log = "0.4.20"
lzma-rs = "0.3.0"
rand = "0.8.5"
rayon = "1.8.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.109"
symphonia = { version = "0.5.3", features = ["all"] }
ybot_fmt =  { path = "ybot_fmt" }
